title: "Розробка проєктів засобами платформи .NET"
description: "Практичні роботи з дисципліни: 8 практичних + вступний гайд налаштування середовища"
theme: jekyll-theme-cayman

plugins:
  - jekyll-relative-links
  - jekyll-readme-index

relative_links:
  enabled: true
  collections: true

readme_index:
  with_frontmatter: false
