site_name: "Розробка проєктів засобами платформи .NET"
site_description: "Документація до дисципліни Розробка проєктів засобами платформи .NET"
repo_url: https://github.com/mypo-vntu/vntu-dotnet-pract
repo_name: mypo-vntu/vntu-dotnet-pract

docs_dir: site-docs
site_dir: site

theme:
  name: shadcn
  show_title: true
  show_stargazers: true
  pygments_style:
    light: shadcn-light
    dark: github-dark

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - fenced_code
  - codehilite
  - pymdownx.magiclink
  - pymdownx.snippets:
      base_path: ["."]
      check_paths: true

nav:
  - Головна: index.md
  - Налаштування середовища: 00-setup.md
  - "ПР1. C# основи": 01-csharp-basics.md
