site_name: "Розробка проєктів засобами платформи .NET"
site_description: "Документація до дисципліни Розробка проєктів засобами платформи .NET"
repo_url: https://github.com/mypo-vntu/vntu-dotnet-pract
repo_name: mypo-vntu/vntu-dotnet-pract

docs_dir: site-docs
site_dir: site

theme:
  name: material
  language: uk
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Темна тема
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Світла тема
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - content.code.copy
    - toc.integrate
    - search.suggest

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.snippets:
      base_path: ["."]
      check_paths: true

nav:
  - Головна: index.md
  - Налаштування середовища: 00-setup.md
  - Практичні роботи: practs/index.md
  - Лекції: lectures.md
